package com.js.mcp.stock.dto;

import com.js.mcp.stock.jpa.Stock;
import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class StockDto {
    private String symbol;
    private String assetType;
    private String name;
    private String description;
    private String cik;
    private String exchange;
    private String currency;
    private String country;
    private String sector;
    private String industry;
    private String address;
    private String fiscalYearEnd;
    private String latestQuarter;
    private Long marketCapitalization;
    private Long ebitda;
    private Double peRatio;
    private Double pegRatio;
    private Double bookValue;
    private Double dividendPerShare;
    private Double dividendYield;
    private Double eps;
    private Double revenuePerShareTTM;
    private Double profitMargin;
    private Double operatingMarginTTM;
    private Double returnOnAssetsTTM;
    private Double returnOnEquityTTM;
    private Long revenueTTM;
    private Long grossProfitTTM;
    private Double dilutedEPSTTM;
    private Double quarterlyEarningsGrowthYOY;
    private Double quarterlyRevenueGrowthYOY;
    private Double analystTargetPrice;
    private Integer analystRatingStrongBuy;
    private Integer analystRatingBuy;
    private Integer analystRatingHold;
    private Integer analystRatingSell;
    private Integer analystRatingStrongSell;
    private Double trailingPE;
    private Double forwardPE;
    private Double priceToSalesRatioTTM;
    private Double priceToBookRatio;
    private Double evToRevenue;
    private Double evToEBITDA;
    private Double beta;
    private Double _52WeekHigh;
    private Double _52WeekLow;
    private Double _50DayMovingAverage;
    private Double _200DayMovingAverage;
    private Long sharesOutstanding;
    private String dividendDate;
    private String exDividendDate;

    public Stock toEntity() {
        Stock stock = new Stock();
        stock.setSymbol(this.symbol);
        stock.setAssetType(this.assetType);
        stock.setName(this.name);
        stock.setDescription(this.description);
        stock.setCik(this.cik);
        stock.setExchange(this.exchange);
        stock.setCurrency(this.currency);
        stock.setCountry(this.country);
        stock.setSector(this.sector);
        stock.setIndustry(this.industry);
        stock.setAddress(this.address);
        stock.setFiscalYearEnd(this.fiscalYearEnd);
        stock.setLatestQuarter(this.latestQuarter);
        stock.setMarketCapitalization(this.marketCapitalization);
        stock.setEbitda(this.ebitda);
        stock.setPeRatio(this.peRatio);
        stock.setPegRatio(this.pegRatio);
        stock.setBookValue(this.bookValue);
        stock.setDividendPerShare(this.dividendPerShare);
        stock.setDividendYield(this.dividendYield);
        stock.setEps(this.eps);
        stock.setRevenuePerShareTTM(this.revenuePerShareTTM);
        stock.setProfitMargin(this.profitMargin);
        stock.setOperatingMarginTTM(this.operatingMarginTTM);
        stock.setReturnOnAssetsTTM(this.returnOnAssetsTTM);
        stock.setReturnOnEquityTTM(this.returnOnEquityTTM);
        stock.setRevenueTTM(this.revenueTTM);
        stock.setGrossProfitTTM(this.grossProfitTTM);
        stock.setDilutedEPSTTM(this.dilutedEPSTTM);
        stock.setQuarterlyEarningsGrowthYOY(this.quarterlyEarningsGrowthYOY);
        stock.setQuarterlyRevenueGrowthYOY(this.quarterlyRevenueGrowthYOY);
        stock.setAnalystTargetPrice(this.analystTargetPrice);
        stock.setAnalystRatingStrongBuy(this.analystRatingStrongBuy);
        stock.setAnalystRatingBuy(this.analystRatingBuy);
        stock.setAnalystRatingHold(this.analystRatingHold);
        stock.setAnalystRatingSell(this.analystRatingSell);
        stock.setAnalystRatingStrongSell(this.analystRatingStrongSell);
        stock.setTrailingPE(this.trailingPE);
        stock.setForwardPE(this.forwardPE);
        stock.setPriceToSalesRatioTTM(this.priceToSalesRatioTTM);
        stock.setPriceToBookRatio(this.priceToBookRatio);
        stock.setEvToRevenue(this.evToRevenue);
        stock.setEvToEBITDA(this.evToEBITDA);
        stock.setBeta(this.beta);
        stock.set_52WeekHigh(this._52WeekHigh);
        stock.set_52WeekLow(this._52WeekLow);
        stock.set_50DayMovingAverage(this._50DayMovingAverage);
        stock.set_200DayMovingAverage(this._200DayMovingAverage);
        stock.setSharesOutstanding(this.sharesOutstanding);
        stock.setDividendDate(this.dividendDate);
        stock.setExDividendDate(this.exDividendDate);
        return stock;
    }
}
